# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillguard" do
  version "0.6.2"

  on_macos do
    on_intel do
      sha256 "49fec978248caaff16c21073ff28428ff6728a1f3a45e476632094642eebf133"
      url "https://github.com/OSSAfrica/skillguard/releases/download/v#{version}/skillguard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4bd9d92dc35ae6afc9c3092a5fb50ca1d8ee66adccb564038132fb5e0104c4d3"
      url "https://github.com/OSSAfrica/skillguard/releases/download/v#{version}/skillguard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "571dafb8ce192486071b360b2d59c874cc9f762916fd4fc9e1e1e8367caf4ce8"
      url "https://github.com/OSSAfrica/skillguard/releases/download/v#{version}/skillguard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b76471d4510171f4e876ec291e8c5827e44f48b45f93896a1be2395e53696593"
      url "https://github.com/OSSAfrica/skillguard/releases/download/v#{version}/skillguard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skillguard"
  desc "Security scanner for AI skill definitions"
  homepage "https://github.com/OSSAfrica/skillguard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillguard"

  # No zap stanza required

end
