# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillguard" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "97da22c5f637d38572ee8d3b807d36c8364afe09cbff76b9bb8b90ee03c31090"
      url "https://github.com/OSSAfrica/skillguard/releases/download/v#{version}/skillguard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "954f4b57d4107ab925a8c0830335ba30c7127ac9b031ad581ec2669bf3b54279"
      url "https://github.com/OSSAfrica/skillguard/releases/download/v#{version}/skillguard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e06fb51d3a69a52132d0f06bce92ae1b0e1a1cd012b686bc9128c3af70f13e95"
      url "https://github.com/OSSAfrica/skillguard/releases/download/v#{version}/skillguard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "80f97a739b94792b90de92e887d1227a7f6cd0f995928095197179d4753442b9"
      url "https://github.com/OSSAfrica/skillguard/releases/download/v#{version}/skillguard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skillguard"
  desc "Security scanner for AI skill definitions"
  homepage "https://github.com/OSSAfrica/skillguard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillguard"

  # No zap stanza required

end
