# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillguard" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "8987fcf5c1cbd7953756719e7a91a7907758e9ec01c4c2d76de8532d129f6951"
      url "https://github.com/OSSAfrica/skillguard/releases/download/v#{version}/skillguard_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a97936f9a5bf3e5dd4be4da247271857d7e13201d325284db0a149157232756e"
      url "https://github.com/OSSAfrica/skillguard/releases/download/v#{version}/skillguard_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a949d90b7f2b6659199d91ad760dfdc5a511295f2419e03d0f82df906ff26dac"
      url "https://github.com/OSSAfrica/skillguard/releases/download/v#{version}/skillguard_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "48c8b06e88528941502e9132a50d2512ffa19e8ead30844cf0ff12322a18dd74"
      url "https://github.com/OSSAfrica/skillguard/releases/download/v#{version}/skillguard_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skillguard"
  desc "Security scanner for AI skill definitions"
  homepage "https://github.com/OSSAfrica/skillguard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillguard"

  # No zap stanza required
end
